version: '3.8'

services:
  catalog-service:
    build: ./services/catalog-service
    ports:
      - "3001:3001"

  order-service:
    build: ./services/order-service
    ports:
      - "3002:3002"

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - catalog-service
      - order-service
